apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-customconfig
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if .Values.pihole.customConfig }}
  05-custom.conf:
    {{ toYaml .Values.pihole.customConfig | indent 4 }}
  {{ end }}
